findahome/findahome/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
#from properties import views

from django.conf.urls.static import static
from users.views import login_view,signup_view,logout_view,ChangePassword,forgetpswd
from properties import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('properties.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('login/',login_view,name='login'),
    path('signup/',signup_view,name='signup'),
    path("logout/", logout_view, name="logout"),
    path("change-password/<token>/",ChangePassword,name="change-password"),
    path("forgetpswd/",forgetpswd, name="forgetpswd"),   
    path("owner/",include('owner.urls')),   
    path('thanks/<int:reservation_id>/', views.thanks, name='thanks'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

findahome/owner/urls.py
from django.urls import path
from .views import properties_views,add_property, delete_property, update_property,request_views,accept_request,decline_request,other_request,view_maintenance_requests,price_prediction
#from .views import rental_map

app_name='owner'

urlpatterns = [
    path('',properties_views,name='properties'),
    path('add_property/',add_property,name='add_property'),
    path('delete_property/<int:property_id>/',delete_property,name='delete_property'),
    path('update_property/<int:property_id>/',update_property,name='update_property'),
    path('request/',request_views,name='request'),
    path('other-requests/',other_request, name='other_requests'),
    path('accept-request/<int:request_id>/',accept_request, name='accept_request'),
    path('decline-request/<int:request_id>/',decline_request, name='decline_request'),
    #path('map/', rental_map, name='rental_map'),
    path('view_maintenance_requests/',view_maintenance_requests,name='view_maintenance_requests'),
    path('price_prediction/',price_prediction,name='price_prediction'),
]

findahome/properties/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.utils import timezone
from django.urls import reverse
from users.models import User
from .constants import PENDING, CANCELLED, EARLY_OCCUPIED,ACTIVE,PAYMENT_PENDING
from django.core.validators import FileExtensionValidator
from location_field.models.plain import PlainLocationField


class District(models.Model):
    name = models.CharField(max_length=50,unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'district'
        verbose_name_plural = 'districts'

    def __str__(self):
        return self.name

class Property(models.Model):
    title = models.CharField(max_length=230)
    description = models.TextField()
    no_of_floors = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    
    no_of_bathrooms_inside= models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    no_of_bathrooms_outside= models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(12)])
    no_of_bedrooms = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    master_bedroon = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    
    no_of_livingrooms = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    dining_hall = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    kitchen = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])


    feature_1 = models.CharField( max_length=100)
    feature_2 = models.CharField( max_length=100)

    plot_area = models.PositiveIntegerField(validators=[MinValueValidator(500)]) # sqft
    
    rate = models.DecimalField(max_digits=6, decimal_places=2)

    has_watersupply = models.BooleanField(default=True)
    has_electricity = models.BooleanField(default=True)

    address_1 = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    zip_code = models.CharField(max_length=6, validators=[RegexValidator(regex='^[0-9]{6}$', message='Invalid Zip Code')])
    video_file = models.FileField(upload_to='properties/',validators=[FileExtensionValidator(['mp4', 'avi'])])
    

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    location = PlainLocationField(based_fields=['city'], zoom=7,null=True,blank=True,default='')

    is_occupied = models.BooleanField(default=False)

    created_at = models.DateTimeField(default=timezone.now) # can be edited/updated manually
    updated_at = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('properties:detail', args=[self.id])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'property'
        verbose_name_plural = 'properties'

class PropertyImages(models.Model):
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='properties/')


    def __str__(self):
        return self.property_id.title
    
    # class Meta:
    #     verbose_name = 'propertyimage'
    #     verbose_name_plural = 'Property Images'

class Wishlist(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)

    created_at = models.DateTimeField(default=timezone.now) # can be edited/updated manually
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return f'{self.user_id.first_name} - {self.property_id.title}'

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'wishlist'
        verbose_name_plural = 'wishlists'

class Reservation(models.Model):
    ALL_STATUSES = [
        (PENDING, "Pending"),
        (CANCELLED, "Cancelled"),
        (EARLY_OCCUPIED,"Early Occupied"),
        (ACTIVE,"Active"),
        (PAYMENT_PENDING,"Payment Pending"),
    ]

    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=ALL_STATUSES, default=PENDING)

    created_at = models.DateTimeField(default=timezone.now) # can be edited/updated manually
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.property_id.title + " - " + self.user_id.first_name

    

class Comment(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    
    comment=models.TextField()
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

    created_at = models.DateTimeField(auto_now_add=True)
    
    

    def __str__(self):
        return self.comment


class MaintenanceRequest(models.Model):
    
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.description


# class Lease(models.Model):
#     user_id = models.ForeignKey(User, on_delete=models.CASCADE)
#     property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
#     start_date = models.DateField()
#     end_date = models.DateField()

#     def __str__(self):
#         return f"{self.user_id} - {self.property_id}"




    
    

findahome/owner/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from properties.forms import PropertyForm,PropertyImageForm
from properties.models import Property,PropertyImages,Reservation
from properties.constants import PENDING, CANCELLED, ACTIVE,EARLY_OCCUPIED,PAYMENT_PENDING
from django.shortcuts import get_object_or_404
from django.forms import modelformset_factory
from properties.models import MaintenanceRequest
import os
# from .forms import MaintenanceRequestForm
# import googlemaps
# API_KEY = 'AIzaSyAtDBI_DGeh1WZEejPVXosbD1NL1KqLNOo'


def properties_views(request):
   properties = Property.objects.filter(owner=request.user).order_by('-created_at')

   return render(request,'owner/properties.html',{'properties':properties})


def add_property(request):
    ImageFormset = modelformset_factory(PropertyImages, fields=('image',), extra=2)

    if request.method == "POST":
        form = PropertyForm(request.POST,request.FILES)
        #video_form = PropertyForm(request.POST, request.FILES)
        formset = ImageFormset(request.POST, request.FILES, queryset=PropertyImages.objects.none())
        

        # do form validation for each field
        if form.is_valid() and formset.is_valid():
            # add the property via form instance's save() method
            # obj is the Property obj
            obj = form.save(commit=False)
            obj.owner = request.user
            obj.save()

            # video = video_form.save(commit=False)
            # video.property_id=obj
            # video.save()

           

            # saving each image
            for f in formset:
                # create an instance of PropertyImages if there is an 'image' present in the form
                # obj is the PropertyImage obj
                if f.cleaned_data.get('image'):
                    image_obj = f.save(commit=False)
                    image_obj.property_id = obj
                    image_obj.save()
            
            messages.success(request, "Property has been added successfully")
            return redirect('owner:properties')
    else:
        form = PropertyForm()
        formset = ImageFormset(queryset=PropertyImages.objects.none())
        # video_form = PropertyImageForm()
      
    return render(request, 'owner/add_property.html', {"form": form, 'formset': formset})

    # if request.method == "POST":
    #     form = PropertyForm(request.POST)
    #     image_form = PropertyImageForm(request.POST,request.FILES)

    #     if form.is_valid() and image_form.is_valid():
       
    #         obj = form.save(commit=False)
    #         obj.owner = request.user
    #         obj.save()

    #         img = image_form.save(commit=False)
    #         img.property_id=obj
    #         img.save()
            
    #         messages.success(request, "Property has been added successfully")
    #         return redirect('owner:properties')
    # else:
    #     form = PropertyForm()
    #     image_form = PropertyImageForm()
    # return render(request,'owner/add_property.html', {'form':form,'image_form':image_form})


def update_property(request, property_id):
    p = get_object_or_404(Property, id=property_id, owner=request.user)
    
    ImageFormset = modelformset_factory(PropertyImages, fields=('image',), extra=2, can_delete=True)
    #ImageFormset = modelformset_factory(PropertyImages, form=PropertyImageForm, fields=('image',), extra=2, can_delete=True)

    if request.method == "POST":
        form = PropertyForm(request.POST,request.FILES,instance=p)
        formset = ImageFormset(request.POST, request.FILES, queryset=PropertyImages.objects.filter(property_id=p.id))
       
  

        # do form validation for each field
        if form.is_valid() and formset.is_valid():   # and video_form.is_valid()
            form.save()



            # if 'delete_video' in request.POST:
            #     if p_video:
            #       os.remove(p_video.video_file.path)
            #       p_video.delete()
            #     image_form.instance.video_file = None
            # elif 'video_file' in request.FILES:
            #     if p_video:
            #       os.remove(p_video.video_file.path)
            #     image_form.save()
            # else:
            #   image_form.save(commit=False)
            #   image_form.video_file = p_video.video_file
            #   image_form.save()
#Check if the video file has changed
            # if 'video_file' in request.FILES:
            #     # Delete the old video file
            #     if p_video:
            #         os.remove(p_video.video_file.path)
            #     # Save the new video file
            #     image_form.save()
            # else:
            #     image_form.save(commit=False)
            #     image_form.video_file = p_video.video_file
            #     image_form.save()
            
        
            # this will give you all forms marked as DELETE
            forms_to_delete = formset.deleted_forms
            for f in formset:
                # create an instance of PropertyImages if there is an 'image' present in the form
                if f.cleaned_data.get('image'):
                        property_image = f.save(commit=False)
                        property_image.property_id = p
                        property_image.save()

                        if f in forms_to_delete:
                            property_image.delete()
            print(form.cleaned_data.get('is_occupied'))
            if not form.cleaned_data.get('is_occupied'):
                reservations=Reservation.objects.filter(property_id=property_id,status=ACTIVE)
                print(reservations)
                if len(reservations)>0:
                    for reservation in reservations:
                        reservation.status=EARLY_OCCUPIED
                        reservation.save()
                
                        
            messages.success(request, "Property has been updated successfully")
            return redirect('owner:properties')
    else:
        form = PropertyForm(instance=p)
        formset = ImageFormset(queryset=PropertyImages.objects.filter(property_id=p.id))
       
    return render(request, 'owner/update_property.html', {"form": form, 'formset': formset})    #,'video_form':video_form

    # p = get_object_or_404(Property, id=property_id, owner=request.user)
    # p_image = PropertyImages.objects.filter(property_id=p.id).first()

    # if request.method == "POST":
    #     form = PropertyForm(request.POST, instance=p)
    #     image_form = PropertyImageForm(request.POST,request.FILES,instance=p_image)
        
        
    #     if form.is_valid() and image_form.is_valid():
    #         form.save()
    #         image_form.save()
            
    #         messages.success(request, "Property has been updated successfully")
    #         return redirect('owner:properties')
    # else:
    #     form = PropertyForm(instance=p)
    #     image_form = PropertyImageForm(instance=p_image)

    # return render(request, 'owner/update_property.html', {"form": form,'image_form':image_form})


def delete_property(request, property_id):
    p = get_object_or_404(Property, id=property_id, owner=request.user)
  

    if request.method == "POST":
        p.delete()
       
        messages.success(request, "Property has been deleted successfully")
        return redirect('owner:properties')

    return render(request, 'owner/delete_confirmation.html', {"property": p})

def request_views(request):
   reservations = Reservation.objects.filter(property_id__owner=request.user, status=PENDING).order_by('-created_at')

   return render(request,'owner/request.html',{"reservations":reservations})

def accept_request(request, request_id):
    r = get_object_or_404(Reservation, id=request_id, property_id__owner=request.user, status=PENDING)

    if request.method == "POST":
        property = Property.objects.get(id=r.property_id.id)
       
        Reservation.objects.filter(property_id=property.id, status=PENDING).exclude(id=r.id).update(status=CANCELLED)

        r.status =PAYMENT_PENDING
        r.save()
        
       
        messages.success(request, "Reservation request for that property has been confirmed successfully")
        return redirect('owner:request')

    return render(request, 'owner/acceptConfirmation.html')



def decline_request(request, request_id):
    r = get_object_or_404(Reservation, id=request_id, property_id__owner=request.user, status=PENDING)

    if request.method == "POST":
        r.status = CANCELLED
        r.save()
        messages.success(request, "Reservation request has been declined successfully")
        return redirect('owner:request')

    return render(request, 'owner/declineConfirmation.html')

def other_request(request):
    
    
    reservations = Reservation.objects.filter(property_id__owner=request.user).exclude(status=PENDING).order_by('-created_at')
       
    return render(request, 'owner/request_history.html',{"reservations":reservations})

# def rental_map(request):
#     gmaps = googlemaps.Client(key=API_KEY)
#     # Do something with the Google Maps client, e.g. retrieve the owner's rental properties
#     return render(request, 'owner/map.html', context)

# def rental_map(request):
#     gmaps = googlemaps.Client(key=API_KEY)
#     properties = get_owner_properties(request.user)
#     markers = []
#     for property in properties:
#         location = gmaps.geocode(property.address)[0]['geometry']['location']
#         markers.append({
#             'lat': location['lat'],
#             'lng': location['lng'],
#             'title': property.name,
#         })
#     context = {
#         'markers': markers,
#     }
#     return render(request, 'owner/map.html', context)

def view_maintenance_requests(request):
    properties = Property.objects.filter(owner=request.user.id)

    maintenance_requests = MaintenanceRequest.objects.filter(property_id__in=properties)

findahome/owner/templates/owner/acceptConfirmation.html
{% extends 'base_owner.html' %}
{% load static %}

{% block title %}Find your sweet home{% endblock %}

{% block tags %}{% endblock %}

{% block content %}
    <div class="properties-page">
        <h1 class="text-2xl font-bold mb-6">Accept Property</h1>
        <p>Accpet this Reservation Request?</p>
        <form method="POST" enctype="multipart/form-data" novalidate class="form w-full">
            {% csrf_token %}
            
            <div class="buttons mt-2 w-64 flex items-center gap-x-4">
                <a href="{% url 'owner:request' %}" class="btn btn-gray text-center w-full font-bold mt-8 mb-4">Go Back</a>
                <button type="submit" class="btn btn-success w-full font-bold mt-8 mb-4">Accept</button>
            </div>
        </form>
    </div>
{% endblock %}

findahome/owner/templates/owner/declineConfirmation.html
{% extends 'base_owner.html' %}
{% load static %}

{% block title %}Find your sweet home{% endblock %}

{% block tags %}{% endblock %}

{% block content %}
    <div class="properties-page">
        <h1 class="text-2xl font-bold mb-6">Decline Request</h1>
        <p>Decline this Reservation Request?</p>
        <form method="POST" enctype="multipart/form-data" novalidate class="form w-full">
            {% csrf_token %}
            
            <div class="buttons mt-2 w-64 flex items-center gap-x-4">
                <a href="{% url 'owner:request' %}" class="btn btn-gray text-center w-full font-bold mt-8 mb-4">Go Back</a>
                <button type="submit" class="btn btn-danger w-full font-bold mt-8 mb-4">Decline</button>
            </div>
        </form>
    </div>
{% endblock %}

findahome/owner/templates/owner/delete_confirmation.html
{% extends 'base_owner.html' %}
{% load static %}

{% block title %}Find your sweet home{% endblock %}

{% block tags %}{% endblock %}

{% block content %}
    <div class="properties-page">
        <h1 class="text-2xl font-bold mb-6">Delete Property</h1>
        <p>Are you sure you want to delete this Property?</p>
        <form method="POST" class="form w-full">
            {% csrf_token %}
            
            <div class="buttons mt-2 w-64 flex items-center gap-x-4">
                <a href="{% url 'owner:properties' %}" class="btn btn-gray text-center w-full font-bold mt-8 mb-4">Go Back</a>
                <button type="submit" class="btn btn-primary w-full font-bold mt-8 mb-4">Delete</button>
            </div>
        </form>
    </div>
{% endblock %}

findahome/owner/templates/owner/map.html
{% extends 'base.html' %}

{% block content %}
<div id="map"></div>
{% endblock %}

{% block scripts %}
<script src="https://maps.googleapis.com/maps/api/js?key={{ API_KEY }}&amp;callback=initMap"
    async defer></script>
<script>
function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: {lat: {{ markers.0.lat }}, lng: {{ markers.0.lng }}},
    });
    {% for marker in markers %}
    var marker = new google.maps.Marker({
        position: {lat: {{ marker.lat }}, lng: {{ marker.lng }}},
        map: map,
        title: '{{ marker.title }}',
    });
    {% endfor %}
}
</script>
{% endblock %} 

{% comment %} 
<a href="{% url 'rentals:rental_map' %}">View rental map</a> {% endcomment %}

findahome/owner/templates/owner/properties.html
{% extends 'base_owner.html' %}
{% load static %}

{% block title %}Find your sweet home{% endblock %}

{% block tags %}{% endblock %}

{% block content %}
    <div class="properties-page">
        <h1 class="text-2xl font-bold mb-6">All Properties</h1>
        <div class="top flex items-center justify-end gap-x-2 mb-4">
            <a href="{% url 'owner:add_property' %}"  class="btn btn-success flex items-center gap-x-1">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v12m6-6H6" />
                  </svg>                  
                Add Property
                </a>
        </div>
        
        <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                  <table class="min-w-full text-center">
                    <thead class="border-b bg-gray-800">
                     
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Img
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Title
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          City
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          District
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                            Zip Code
                          </th>
                          <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                            Is Occupied
                          </th>
                          <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                            Actions
                          </th>
                        </thead>
                   
                    <tbody>
                      {% for property in properties %}
                        <tr class="bg-white border-b">
                          <!--<td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">   {{property.image}}</td>-->
                          <td>
                            {% if property.propertyimages_set.first %}
                                <img class="h-10 w-10 object-cover" src="{{ property.propertyimages_set.first.image.url }}" alt="property">
                            {% else %}
                               
                                <img class="h-10 w-10 object-cover" src="{% static 'img/fallback.png' %}" alt="fallback">
                            {% endif %}
                        </td>
                          
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            {{property.title}}
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            {{property.city}}
                          
                            </td>
                            <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                              {{property.district}}
                            </td>
                            <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                              {{property.zip_code}}
                            </td>
                            <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                              {{property.is_occupied}}
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                              <a href="{% url 'owner:update_property' property_id=property.id %}" class="btn btn-success">Edit</a>
                             
                              <a href="{% url 'owner:delete_property' property_id=property.id %}" class=" btn btn-danger">Delete</a>    
                          </td>
                        
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>            
{% endblock %}

findahome/owner/templates/owner/request.html
{% extends 'base_owner.html' %}
{% load static %}

{% block title %}Find your sweet home{% endblock %}

{% block tags %}{% endblock %}

{% block content %}
<div>
    <h1 class="text-2xl font-bold mb-6"> Pending Request</h1>
</div>
<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full text-center">
            <thead class="border-b bg-gray-800">
             
                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                 User
                </th>
                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                  Property
                </th>
                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                  Actions
                </th>
                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                 Booking Status
                </th>
                </thead>
           
            <tbody>
                
               {% for r in reservations %}
                        <tr class="bg-white border-b">
                          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"> {{r.user_id.first_name}} {{r.user_id.last_name}}</td>
                        </td>
                          
                          <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap">
                            {{r.property_id.title}}
                          </td>
                         
                           <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            <a href="{% url 'owner:accept_request' request_id=r.id %}" class="btn btn-success py-1.5">Accept</a>
                            <a href="{% url 'owner:decline_request' request_id=r.id %}" class="btn btn-danger py-1.5">Decline</a>
                            <!--<button type="submit" class="btn btn-success">Approval</button>
                             <button type="submit" class="btn btn-danger">Reject</button>--> 
                           
                          </td>
                        
                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{r.status}}</td>  
                          </td>
                        
                          </tr>
                        {% endfor %}
                      
            </tbody>
        </table>
    </div>
</div>
</div>
</div>            
{% endblock %}

findahome/owner/templates/owner/request_history.html
{% extends 'base_owner.html' %}
{% load static %}

{% block title %}Find your sweet home{% endblock %}

{% block tags %}{% endblock %}

{% block content %}
<div>
    <h1 class="text-2xl font-bold mb-6"> Request History</h1>
</div>
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center">
          <thead class="border-b bg-gray-800">
           
              <th scope="col" class="text-sm font-medium text-white px-6 py-4">
               User
              </th>
              <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                Property
              </th>
              <th scope="col" class="text-sm font-medium text-white px-6 py-4">
               Status
              </th>
              </thead>
              <tbody>
                
                {% for r in reservations %}
                         <tr class="bg-white border-b">
                           <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"> {{r.user_id.first_name}} {{r.user_id.last_name}}</td>
                         </td>
                           
                           <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap">
                             {{r.property_id.title}}
                           </td>
                          
                        

                    
                         
                          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{r.status}}</td> 
                              
                    
                      </tr>
                      {% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>            
{% endblock %}