findahome/findahome/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
#from properties import views

from django.conf.urls.static import static
from users.views import login_view,signup_view,logout_view,ChangePassword,forgetpswd
from properties import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('properties.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('login/',login_view,name='login'),
    path('signup/',signup_view,name='signup'),
    path("logout/", logout_view, name="logout"),
    path("change-password/<token>/",ChangePassword,name="change-password"),
    path("forgetpswd/",forgetpswd, name="forgetpswd"),   
    path("owner/",include('owner.urls')),   
    path('thanks/<int:reservation_id>/', views.thanks, name='thanks'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

findahome/owner/urls.py
from django.urls import path
from .views import properties_views,add_property, delete_property, update_property,request_views,accept_request,decline_request,other_request,view_maintenance_requests,price_prediction
#from .views import rental_map

app_name='owner'

urlpatterns = [
    path('',properties_views,name='properties'),
    path('add_property/',add_property,name='add_property'),
    path('delete_property/<int:property_id>/',delete_property,name='delete_property'),
    path('update_property/<int:property_id>/',update_property,name='update_property'),
    path('request/',request_views,name='request'),
    path('other-requests/',other_request, name='other_requests'),
    path('accept-request/<int:request_id>/',accept_request, name='accept_request'),
    path('decline-request/<int:request_id>/',decline_request, name='decline_request'),
    #path('map/', rental_map, name='rental_map'),
    path('view_maintenance_requests/',view_maintenance_requests,name='view_maintenance_requests'),
    path('price_prediction/',price_prediction,name='price_prediction'),
]

findahome/properties/urls.py
from django.urls import path
from .views import home
from .views import wishlist
from .views import search
from .views import reservation
from .views import property_details
from .views import add_comment
from .views import payment
from .views import thanks
from .views import terms
from .views import property_reserve,add_or_remove_wishlist
from .views import  create_maintenance_request,show_video
app_name='properties'

urlpatterns = [
    path('',home,name='home'),
    path('search/', search, name='search'),
    path('wishlist/',wishlist,name='wishlist'),
    path('reservation/',reservation,name='reservations'),
    path('property_details/<int:propertydetails_id>/',property_details,name='property_details'),
    path('property/reserve',property_reserve,name='property_reserve'),
    path('wishlists/property/<int:propertydetails_id>/',add_or_remove_wishlist, name='add_or_remove_wishlist'),
    path('property/<int:id>/add-comment', add_comment, name='add_comment'),
    path('payment/<int:property_id>/',payment,name='payment'),
    path('terms/<int:property_id>/',terms,name='terms'),
    path('maintenance_request/<int:property_id>/', create_maintenance_request,name='maintenancerequest'),
    #path('property/<int:property_id>/show_video/', show_video, name='show_video'),
    #path('show_video/<int:property_id>/', show_video, name='show_video'),
    path('show_video/<int:property_id>/', show_video, name='show_video'),
]

findahome/properties/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.utils import timezone
from django.urls import reverse
from users.models import User
from .constants import PENDING, CANCELLED, EARLY_OCCUPIED,ACTIVE,PAYMENT_PENDING
from django.core.validators import FileExtensionValidator
from location_field.models.plain import PlainLocationField


class District(models.Model):
    name = models.CharField(max_length=50,unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'district'
        verbose_name_plural = 'districts'

    def __str__(self):
        return self.name

class Property(models.Model):
    title = models.CharField(max_length=230)
    description = models.TextField()
    no_of_floors = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    
    no_of_bathrooms_inside= models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    no_of_bathrooms_outside= models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(12)])
    no_of_bedrooms = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    master_bedroon = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    
    no_of_livingrooms = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    dining_hall = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])
    kitchen = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(12)])


    feature_1 = models.CharField( max_length=100)
    feature_2 = models.CharField( max_length=100)

    plot_area = models.PositiveIntegerField(validators=[MinValueValidator(500)]) # sqft
    
    rate = models.DecimalField(max_digits=6, decimal_places=2)

    has_watersupply = models.BooleanField(default=True)
    has_electricity = models.BooleanField(default=True)

    address_1 = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    zip_code = models.CharField(max_length=6, validators=[RegexValidator(regex='^[0-9]{6}$', message='Invalid Zip Code')])
    video_file = models.FileField(upload_to='properties/',validators=[FileExtensionValidator(['mp4', 'avi'])])
    

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    location = PlainLocationField(based_fields=['city'], zoom=7,null=True,blank=True,default='')

    is_occupied = models.BooleanField(default=False)

    created_at = models.DateTimeField(default=timezone.now) # can be edited/updated manually
    updated_at = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('properties:detail', args=[self.id])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'property'
        verbose_name_plural = 'properties'

class PropertyImages(models.Model):
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='properties/')


    def __str__(self):
        return self.property_id.title
    
    # class Meta:
    #     verbose_name = 'propertyimage'
    #     verbose_name_plural = 'Property Images'

class Wishlist(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)

    created_at = models.DateTimeField(default=timezone.now) # can be edited/updated manually
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return f'{self.user_id.first_name} - {self.property_id.title}'

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'wishlist'
        verbose_name_plural = 'wishlists'

class Reservation(models.Model):
    ALL_STATUSES = [
        (PENDING, "Pending"),
        (CANCELLED, "Cancelled"),
        (EARLY_OCCUPIED,"Early Occupied"),
        (ACTIVE,"Active"),
        (PAYMENT_PENDING,"Payment Pending"),
    ]

    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=ALL_STATUSES, default=PENDING)

    created_at = models.DateTimeField(default=timezone.now) # can be edited/updated manually
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.property_id.title + " - " + self.user_id.first_name

    

class Comment(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    
    comment=models.TextField()
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

    created_at = models.DateTimeField(auto_now_add=True)
    
    

    def __str__(self):
        return self.comment


class MaintenanceRequest(models.Model):
    
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.description


# class Lease(models.Model):
#     user_id = models.ForeignKey(User, on_delete=models.CASCADE)
#     property_id = models.ForeignKey(Property, on_delete=models.CASCADE)
#     start_date = models.DateField()
#     end_date = models.DateField()

#     def __str__(self):
#         return f"{self.user_id} - {self.property_id}"




    
    

findahome/properties/forms.py
from django import forms

from .models import Property,PropertyImages
from .models import MaintenanceRequest

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('title', 'description', 'no_of_floors', 'no_of_bathrooms_inside','no_of_bathrooms_outside','no_of_bedrooms','master_bedroon','no_of_livingrooms','kitchen','dining_hall','kitchen','feature_1','feature_2','plot_area','rate','has_electricity','has_watersupply','address_1','city','district','zip_code','is_occupied','video_file','location')
     
class PropertyImageForm(forms.ModelForm):
    class Meta:
        model = PropertyImages
        fields = ('image',)   
       

class MaintenanceRequestForm(forms.ModelForm):
    class Meta:
        model = MaintenanceRequest
        fields = ['description']



       

findahome/properties/templates/properties/maintenance_request.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Find your sweet home{% endblock %}
{% block content %}
<form method="POST" > 
    {% csrf_token %}
{{form}}
<button type="submit" >SEND MESSAGE</button>

</form>


{% endblock %}

findahome/properties/templates/properties/reservation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Find your sweet home{% endblock %}

{% block content %}
   
        
        <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                  <table class="w-full text-center table-fixed inset-y-0 right-0">
                    <thead class="border-b bg-gray-800">
                        
                     
                        <th scope="col" class="text-sm font-medium text-white px-4 py-4">
                          Img
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Title
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          City
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          District
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Rate
                        </th>
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                          Status
                         </th>
                          <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                           Action
                          </th>
                        </thead>
                   
                    <tbody>
                      {% for reservation in reservations %}
                        <tr class="bg-white border-b text-center">
                          {% comment %} <td  class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">   {{property.image}} </td> {% endcomment %}
                          <td>
                            {% if reservation.property_id.propertyimages_set.first %}
                                <img class="h-10 w-15 object-cover  right-4 mx-auto my-auto block" src="{{ reservation.property_id.propertyimages_set.first.image.url }}" alt="property">
                            {% else %}
                               
                                <img class="h-10 w-10 object-cover" src="{% static 'img/fallback.png' %}" alt="fallback">
                            {% endif %}
                        </td>
                          
                          <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap">
                            <a href="{% url 'properties:property_details' propertydetails_id=reservation.property_id.id%}">
                            {{reservation.property_id.title}}</a>
                          </td>
                          <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap">
                            {{reservation.property_id.city}}
                          
                            </td>
                            <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap">
                              {{reservation.property_id.district}}
                            </td>
                          </td>
                          <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap">
                            {{reservation.property_id.rate}}
                          </td>
                          <td class="text-sm text-gray-900 font-medium px-6 py-4 whitespace-nowrap">
                            {{reservation.status}}
                          </td>
                          <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                           {% if reservation.status == "PAYMENT_PENDING" %}
                           <a href="{% url 'properties:terms' property_id=reservation.property_id.id %}" >
                            <button class="bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded">
                             Proceed To Pay
                            </button></a>
                           {% endif %}
                           {% if reservation.status == "ACTIVE" or reservation.status == "EARLY_OCCUPIED" %}
                           <a href="" >
                            <button class="bg-green-500 hover:bg-green-400 text-white font-bold py-2 px-4 border-b-4 border-green-700 hover:border-green-500 rounded">
                            View Receipt
                            </button></a>
                           {% endif %}
                           
                             
                              {% comment %} <a href="{% url 'owner:delete_property' property_id=property.id %}" class=" btn btn-danger">Delete</a>     {% endcomment %}
                          </td>
                        
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>            
{% endblock %}

findahome/properties/templates/properties/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Search Results{% endblock %}

{% block tags %}{% endblock %}

{% block content %}
    <div class="search-page flex">
        <section class="filters sticky w-64 px-4 pt-4 border-r min-h-screen">
            <h3 class="font-bold mb-4">Filters</h3>

            <form action="" method="GET">
                <input type="hidden" name="q" value="{{ q }}">
                
                <div class="form-group mb-4">
                    <label>Budget</label>
                    <div class="inputs flex items-center gap-x-2">
                        <input min="{{ min_price }}" max="{{ max_price }}" id="min-price" name="min-price" type="number" value="{{ current_min_price }}" placeholder="Min" class="text-sm">
                        <input min="{{ min_price }}" max="{{ max_price }}" id="max-price" name="max-price" type="number" value="{{ current_max_price }}" placeholder="Max" class="text-sm">
                    </div>
                </div>

                <div class="form-group mb-4">
                    <label for="floors">Floors</label>

                    <div class="input-num">
                        <button  class="dec-btn" type="button">-</button>
                        <input id="floor-input" name="floors" type="number" min="{{ min_no_of_floors }}" max="{{ max_no_of_floors }}" value="{{ current_no_of_floors }}">
                        <button  type="button" class="inc-btn">+</button>
                    </div>
                </div>

                <div class="form-group mb-4">
                    <label for="bedrooms">Bedrooms</label>

                    <div class="input-num">
                        <button  class="dec-btn" type="button">-</button>
                        <input id="bed-input" name="bedrooms" type="number" min="{{ min_no_of_bedrooms }}" max="{{ max_no_of_bedrooms }}" value="{{ current_no_of_bedrooms }}">
                        <button  type="button" class="inc-btn">+</button>
                    </div>
                </div>

               

                <div class="form-group mb-4">
                    <label>Sqft</label>
                    <div class="inputs flex items-center gap-x-2">
                        <input min="{{ min_sqft }}" max="{{ max_sqft }}" id="min-sqft" name="min-sqft" type="number" value="{{ current_min_sqft }}" placeholder="Min" class="text-sm">
                        <input min="{{ min_sqft }}" max="{{ max_sqft }}" id="max-sqft" name="max-sqft" type="number" value="{{ current_max_sqft }}" placeholder="Max" class="text-sm">
                    </div>
                </div>

                <div class="buttons flex items-center gap-x-2">
           
                    <button type="submit" class="btn btn-black w-full mt-4">Apply</button>
                </div>
            </form>
        </section>
        <section class="search-results flex-1 px-4 py-6">
            <h1 class="text-2xl font-bold mb-4">Search Results</h1>

            <div class="results flex flex-col gap-y-2">
                {% if properties %}
                    {% for p in properties %}
                        <a href="{% url 'properties:property_details' propertydetails_id=p.id %}" class="property-card shadow p-1 rounded-xl flex gap-x-4 pr-4" style="height: 170px;">
                            <div class="img w-52 h-full">
                                {% if p.propertyimages_set.first %}
                                    <img class="h-full w-full rounded-xl object-cover" src="{{ p.propertyimages_set.first.image.url }}" alt="property">
                                {% else %}
                       
                                    <img class="h-full rounded-xl w-full object-cover" src="{% static 'img/fallback.png' %}" alt="fallback">
                                {% endif %}
                            </div>
                            <div class="right flex-1 flex flex-col justify-between">
                                <div class="top flex flex-col">
                                    <div class="title flex items-center justify-between">
                                        <h3 class="text-xl text-gray-900 font-semibold">{{ p.title}}</h3>
                                        <span class="text-gray-900 text-2xl font-semibold">₹ {{ p.rate}}</span>
                                    </div>
                                    <div class="text-sm text-gray-600 flex items-center gap-x-1">
                                       <!-- <span class="flex items-center"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3.5 h-3.5 fill-gray-500 stroke-gray-500">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
                                      </svg>--></span> {{ p.district.name }}</div>

                                    <p class="text-gray-600 text-sm">Posted on: {{ p.created_at|date:"M d, Y" }}</p>

                                </div>
                                <div class="extras flex items-center justify-between">
                                    <div class="left flex items-center justify-between text-gray-800 gap-x-6">
                                        <div class="floors text-center">
                                            <div class="top flex items-center justify-center gap-x-1">
                                                <svg class="fill-gray-800" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="16" viewBox="0 0 24 24" width="24"><rect fill="none" height="24" width="16"/><path d="M12,7V3H2v18h20V7H12z M10,19H4v-2h6V19z M10,15H4v-2h6V15z M10,11H4V9h6V11z M10,7H4V5h6V7z M20,19h-8V9h8V19z M18,11h-4v2 h4V11z M18,15h-4v2h4V15z"/></svg>
                                                <span class="" style="line-height: 0; font-size: 14px;">{{ p.no_of_floors }}</span>
                                            </div>
                                            <span class="" style="line-height: 0; font-size: 12px;">Floors</span>                               
                                        </div>
                                        <div class="bedrooms text-center">
                                            <div class="top flex items-center justify-center gap-x-1">
                                                <svg class="fill-gray-800" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="16" viewBox="0 0 24 24" width="16"><g><path d="M0,0h24v24H0V0z" fill="none"/></g><g><path d="M21,10.78V8c0-1.65-1.35-3-3-3h-4c-0.77,0-1.47,0.3-2,0.78C11.47,5.3,10.77,5,10,5H6C4.35,5,3,6.35,3,8v2.78 C2.39,11.33,2,12.12,2,13v6h2v-2h16v2h2v-6C22,12.12,21.61,11.33,21,10.78z M14,7h4c0.55,0,1,0.45,1,1v2h-6V8C13,7.45,13.45,7,14,7 z M5,8c0-0.55,0.45-1,1-1h4c0.55,0,1,0.45,1,1v2H5V8z M4,15v-2c0-0.55,0.45-1,1-1h14c0.55,0,1,0.45,1,1v2H4z"/></g></svg>
                                                <span class="" style="line-height: 0; font-size: 14px;">{{ p.no_of_bedrooms }}</span>
                                            </div>
                                            <span class="" style="line-height: 0; font-size: 12px;">Bedrooms</span>                               
                                        </div>
                                        <div class="bathrooms text-center">
                                            <div class="top flex items-center justify-center gap-x-1">
                                                <svg class="fill-gray-700" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="16" viewBox="0 0 24 24" width="16"><g><path d="M0,0h24v24H0V0z" fill="none"/></g><g><circle cx="8" cy="17" r="1"/><circle cx="12" cy="17" r="1"/><circle cx="16" cy="17" r="1"/><path d="M13,5.08V3h-2v2.08C7.61,5.57,5,8.47,5,12v2h14v-2C19,8.47,16.39,5.57,13,5.08z"/><circle cx="8" cy="20" r="1"/><circle cx="12" cy="20" r="1"/><circle cx="16" cy="20" r="1"/></g></svg>
                                                <span class="" style="line-height: 0; font-size: 14px;">{{ p.no_of_bathrooms }}</span>
                                            </div>
                                            <span class="" style="line-height: 0; font-size: 12px;">Bathrooms
                                            </span>                               
                                        </div>
                                        <div class="plot-area text-center">
                                            <div class="top flex items-center justify-center gap-x-1">
                                                <svg class="fill-gray-800" xmlns="http://www.w3.org/2000/svg" height="16" viewBox="0 0 24 24" width="16"><path d="M0 0h24v24H0z" fill="none"/><path d="M17 15h2V7c0-1.1-.9-2-2-2H9v2h8v8zM7 17V1H5v4H1v2h4v10c0 1.1.9 2 2 2h10v4h2v-4h4v-2H7z"/></svg>
                                                <span class="" style="line-height: 0; font-size: 14px;">{{ p.plot_area }} sqft</span>
                                            </div>
                                            <span class="" style="line-height: 0; font-size: 12px;">Area</span>                               
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                {% else %}
                        <p class="pl-8 mt-2 text-gray-500">No Properties found</p>
                {% endif %}
            </div>
        </section>
    </div>
{% endblock %}

findahome/properties/templates/properties/wishlist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Wishlist{% endblock %}

{% block content %}
<main class="wishlist-properties grid grid-cols-1 md:grid-cols-4 gap-6">
    {% if wishlist_properties %}
        {% for w in wishlist_properties %}
            <a href="{% url 'properties:property_details' propertydetails_id=w.property_id.id%} " class="property-card rounded-xl" style="height: 360px;">
                <div class="top border-b">
                    <div class="img relative">
                        {% if w.property_id.propertyimages_set.first %}
                            <img class="h-60 rounded-xl w-full object-cover" src="{{ w.property_id.propertyimages_set.first.image.url }}" alt="property">
                        {% else %}
                            <!-- fallback image -->
                            <img class="h-60 rounded-xl w-full object-cover" src="{% static 'img/fallback.png' %}" alt="fallback">
                        {% endif %}
                       
                    </div>
                    <div class="infos px-2 py-2 flex items-center justify-between">
                        <div class="left leading-tight">
                            <h3 class="text-base text-gray-900 font-semibold">{{ w.property_id.title }}</h3>
                            <div class="text-xs text-gray-700 flex items-center gap-x-1">
                             {{ w.property_id.district.name }}
                            </div>
                        </div>
                        <div class="right text-gray-900 text-lg font-semibold">
                            ₹ {{ w.property_id.rate }}
                        </div>
                    </div>
                </div>
                <div class="extras px-2 py-2 flex items-center justify-between text-gray-800">
                    <div class="flex-1 flex items-center justify-between gap-x-2">
                        <div class="floors text-center">
                            <div class="top flex items-center justify-center gap-x-1">
                                <svg class="fill-gray-800" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="16" viewBox="0 0 24 24" width="24"><rect fill="none" height="24" width="16"/><path d="M12,7V3H2v18h20V7H12z M10,19H4v-2h6V19z M10,15H4v-2h6V15z M10,11H4V9h6V11z M10,7H4V5h6V7z M20,19h-8V9h8V19z M18,11h-4v2 h4V11z M18,15h-4v2h4V15z"/></svg>
                                  <span class="" style="line-height: 0; font-size: 14px;">{{ w.property_id.no_of_floors }}</span>
                            </div>
                            <span class="" style="line-height: 0; font-size: 12px;">Floors</span>                               
                        </div>
                        <div class="bedrooms text-center">
                            <div class="top flex items-center justify-center gap-x-1">
                                <svg class="fill-gray-800" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="16" viewBox="0 0 24 24" width="16"><g><path d="M0,0h24v24H0V0z" fill="none"/></g><g><path d="M21,10.78V8c0-1.65-1.35-3-3-3h-4c-0.77,0-1.47,0.3-2,0.78C11.47,5.3,10.77,5,10,5H6C4.35,5,3,6.35,3,8v2.78 C2.39,11.33,2,12.12,2,13v6h2v-2h16v2h2v-6C22,12.12,21.61,11.33,21,10.78z M14,7h4c0.55,0,1,0.45,1,1v2h-6V8C13,7.45,13.45,7,14,7 z M5,8c0-0.55,0.45-1,1-1h4c0.55,0,1,0.45,1,1v2H5V8z M4,15v-2c0-0.55,0.45-1,1-1h14c0.55,0,1,0.45,1,1v2H4z"/></g></svg>
                                  <span class="" style="line-height: 0; font-size: 14px;">{{ w.property_id.no_of_bedrooms }}</span>
                            </div>
                            <span class="" style="line-height: 0; font-size: 12px;">Bedrooms</span>                               
                        </div>
                        <div class="bathrooms text-center">
                            <div class="top flex items-center justify-center gap-x-1">
                                <svg class="fill-gray-700" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="16" viewBox="0 0 24 24" width="16"><g><path d="M0,0h24v24H0V0z" fill="none"/></g><g><circle cx="8" cy="17" r="1"/><circle cx="12" cy="17" r="1"/><circle cx="16" cy="17" r="1"/><path d="M13,5.08V3h-2v2.08C7.61,5.57,5,8.47,5,12v2h14v-2C19,8.47,16.39,5.57,13,5.08z"/><circle cx="8" cy="20" r="1"/><circle cx="12" cy="20" r="1"/><circle cx="16" cy="20" r="1"/></g></svg>
                                  <span class="" style="line-height: 0; font-size: 14px;">{{ w.property_id.no_of_bathrooms }}</span>
                            </div>
                            <span class="" style="line-height: 0; font-size: 12px;">Bathrooms</span>                               
                        </div>
                        <div class="plot-area text-center">
                            <div class="top flex items-center justify-center gap-x-1">
                                <svg class="fill-gray-800" xmlns="http://www.w3.org/2000/svg" height="16" viewBox="0 0 24 24" width="16"><path d="M0 0h24v24H0z" fill="none"/><path d="M17 15h2V7c0-1.1-.9-2-2-2H9v2h8v8zM7 17V1H5v4H1v2h4v10c0 1.1.9 2 2 2h10v4h2v-4h4v-2H7z"/></svg>
                                  <span class="" style="line-height: 0; font-size: 14px;">{{ w.property_id.plot_area }} sqft</span>
                            </div>
                            <span class="" style="line-height: 0; font-size: 12px;">Area</span>                               
                        </div>
                    </div>
                </div>
            </a>
            {%endfor%}
            {% else %}
            <div><h1>ITEM NOT FOUND</h1></div>
            {%endif%}
            
{% endblock %}