findahome/findahome/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
#from properties import views

from django.conf.urls.static import static
from users.views import login_view,signup_view,logout_view,ChangePassword,forgetpswd
from properties import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('properties.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('login/',login_view,name='login'),
    path('signup/',signup_view,name='signup'),
    path("logout/", logout_view, name="logout"),
    path("change-password/<token>/",ChangePassword,name="change-password"),
    path("forgetpswd/",forgetpswd, name="forgetpswd"),   
    path("owner/",include('owner.urls')),   
    path('thanks/<int:reservation_id>/', views.thanks, name='thanks'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

findahome/owner/urls.py
from django.urls import path
from .views import properties_views,add_property, delete_property, update_property,request_views,accept_request,decline_request,other_request,view_maintenance_requests,price_prediction
#from .views import rental_map

app_name='owner'

urlpatterns = [
    path('',properties_views,name='properties'),
    path('add_property/',add_property,name='add_property'),
    path('delete_property/<int:property_id>/',delete_property,name='delete_property'),
    path('update_property/<int:property_id>/',update_property,name='update_property'),
    path('request/',request_views,name='request'),
    path('other-requests/',other_request, name='other_requests'),
    path('accept-request/<int:request_id>/',accept_request, name='accept_request'),
    path('decline-request/<int:request_id>/',decline_request, name='decline_request'),
    #path('map/', rental_map, name='rental_map'),
    path('view_maintenance_requests/',view_maintenance_requests,name='view_maintenance_requests'),
    path('price_prediction/',price_prediction,name='price_prediction'),
]

findahome/users/models.py
from django.db import models
from django.contrib.auth.models import ( AbstractBaseUser,BaseUserManager)
from .constants import TENANT, OWNER

class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, role=TENANT, password=None):
        if not email:
            raise ValueError('Email is required!')
        if not first_name:
            raise ValueError('First name is required!')
        if not last_name:
            raise ValueError('Last name is required!')

        user = self.model(email=self.normalize_email(email), first_name=first_name, last_name=last_name)

        user.set_password(password)
        user.role = role
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None):
        user = self.create_user(
            email=email,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    
    ALL_ROLES = [
        (TENANT, "Tenant"),
        (OWNER, "Owner"),
    ]

   
    first_name = models.CharField(max_length=100) 
    last_name = models.CharField(max_length=100) 
    email = models.EmailField(max_length=255, unique=True) 
    profile_pic = models.ImageField(upload_to='profile_pics/', default='profile_pics/default.png')
    role = models.CharField(max_length=6, choices=ALL_ROLES, default=OWNER)
    
    is_active = models.BooleanField(default=True) 
    is_staff = models.BooleanField(default=False) 
    is_superuser = models.BooleanField(default=False) 

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

   
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name'] 

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    
    def has_perm(self, perm, obj=None):
        return self.is_superuser
    
    def has_module_perms(self, app_label):
        return True

    def get_all_permissions(user=None):
        if user.is_superuser:
           return set()


class Profile(models.Model):
    user = models.OneToOneField("User", on_delete=models.CASCADE)
    forget_password_token=models.CharField(max_length=100)
    created_at = models.DateTimeField( auto_now_add=True)
   
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

findahome/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User

class LoginForm(forms.Form):
    email = forms.EmailField(label="Email")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class SignupForm(forms.ModelForm):
    
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'role')
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2
    
    def save(self, commit=True):
    
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name','profile_pic', 'role', 'is_active', 'is_superuser', 'is_staff')

    def clean_password(self):
        return self.initial["password"]

findahome/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import LoginForm,SignupForm
from .helpers import send_forget_password_email
from .models import Profile ,User
from .constants import TENANT
import uuid



def login_view(request):

    if ((request.user.is_authenticated)):
        return redirect('properties:home')
    
    common_error = ""

    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

           
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
               
                if user.role == TENANT:
                    return redirect('properties:home')
                else:
                    return redirect('owner:properties')


            else:
                
               common_error = "Invalid email or password"
    else:
        form = LoginForm()

    return render(request, "users/login.html", {'form': form, "common_error": common_error})

def signup_view(request):
    
    if ((request.user.is_authenticated)):
        return redirect('properties:home')
    
    if request.method == "POST":
        form = SignupForm(request.POST)

        
        if form.is_valid():
           
            user_obj =  form.save()

            profile_obj = Profile.objects.create(user = user_obj)
            profile_obj.save()

            messages.success(request, "Your account has been created successfully, please login to continue")
            return redirect('login')
    else:
        form = SignupForm()
    return render(request, "users/signup.html", { "form": form })

def logout_view(request):
    logout(request)
    return redirect("properties:home")

def ChangePassword(request,token):
    context = {}
    try:
        profile_obj = Profile.objects.filter(forget_password_token = token).first()
        context = {'user_id':profile_obj.user.id}
       
        if request.method == 'POST':
            new_password= request.POST.get('new_password')
            print(new_password)
            confirm_password=request.POST.get('reconfirm_password')
            user_id=profile_obj.user.id

        if user_id is None:
            message.success(request,'No user id found')
            return redirect(f'/change-password/{token}/')


        if new_password!= confirm_password:
            message.success(request,'Both shoud be equal.')
            return redirect(f'/change-password/{token}/')


        user_obj= User.objects.get(id = user_id)
        user_obj.set_password(new_password)
        user_obj.save()  
        return redirect('login')  


        print(profile_obj)
       
    except Exception as e:
        print(e)
    return render(request,'users/change-password.html',context)




def forgetpswd(request):
    try:
        if request.method=='POST':
            email=request.POST.get('email')
            

            if not User.objects.filter(email=email).first():
                messages.success(request,'No user found with this email.')
                return redirect('/forgetpswd/')

            user_obj = User.objects.get(email=email)
            token = str(uuid.uuid4())
            profile_obj= Profile.objects.get(user = user_obj)
            profile_obj.forget_password_token = token
            profile_obj.save()
           
            send_forget_password_email(user_obj.email , token)
            messages.success(request,'An email is send.')
            return redirect('/forgetpswd/')


    except Exception as e:
        print(e)
    return render(request,'users/forgetpswd.html')    

   

findahome/users/templates/users/change-password.html
{% extends "base_auth.html"%}
{% block content %}
<div class="container">
    <form class="form"  method ="POST" id ="form">
        {% csrf_token %}
        <h4>Forget Paasword</h4>

        {% if messages %}
    
        {% for message in messages %}
        <div class ="alert alert-info">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}



<div class = "form-group">
    <label for ="password">Password</label>
    <input type ="password" name="new_password" class="form-control">
</div>
<div class = "form-group">
    <label for ="password"> Re confirm Password</label>
    <input type ="password" name="reconfirm_password" class="form-control">
</div>

<input type = "hidden" name="user_id" value="{{user_id}}">
<button class ="btn btn-primary" type="submit">Submit</button>


</form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    function checkPassword() {
        let new_password = document.getElementById
        ("new_password").value;
        let confirm_password = document.getElementById
        (" reconfirm_password").value;
        console.log(new_password,confirm_password);
        let message = document.getElementById
        ("message");


    if(new_password.length!=0) {
        if(new_password == confirm_password){
            message.textContent = "Password Match";
            message.style.backgroundColor="green";
        } else{
        message.textContent = "Password don't Match"
        message.style.backgroundColor="red";
        }
     }
    }
</script>
{% endblock%}

findahome/users/templates/users/forgetpswd.html
{% extends "base_auth.html" %}
{% block content %}
<div class="container">
    <form class="form"  method ="POST" id ="form">
        {% csrf_token %}
        <h4>Forget Paasword</h4>

        {% if messages %}
    
        {% for message in messages %}
        <div class ="alert alert-info">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}

        
        <div class="form-control block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">
        <div class="form-group">
            <label for="password">Email</label>
            <input type="text" name="email" class="form-control">
         <button class ="btn btn-primary" type="submit">Submit</button>

        </form>
    </div>
</div>
{% endblock%}

findahome/users/templates/users/login.html
{% extends "base_auth.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="bg-white shadow">
        <div style="width: 390px;" class="flex flex-col items-center justify-center gap-y-4 px-6 py-4">
            <h1 class="mb-4 font-bold text-3xl text-center">Login</h1>
            <form method="POST" novalidate class="w-full">
              {% csrf_token %}

              <div class="form-group {% if form.email.errors %}error{% endif %}">
                <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                {{ form.email }}
                
                {{ form.email.errors }}
            </div>

            <div class="form-group {% if form.password.errors %}error{% endif %}">
                <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                {{ form.password }}
                
                {{ form.password.errors }}
            </div>
                <div class="text-center pt-1 mb-12 pb-1">
                  
                    
                <button type="submit" class="btn btn-primary w-full font-bold mt-4 mb-4">Login</button>
              </form>
  
              <a href= "{% url 'forgetpswd' %}"class="text-sm">Forgot Password?</a>
  
              <p class="text-sm text-gray-500">Don't have an account?
                  <a href="{% url 'signup' %}" class="font-bold">Signup</a>
              </p>
          </div>
      </div>
  {% endblock %}
                
                
               

findahome/users/templates/users/signup.html
{% extends "base_auth.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="bg-white shadow">
        <div class="flex flex-col items-center justify-center gap-y-4 px-6 py-4 w-full max-w-lg">
            <h1 class="mb-4 font-bold text-3xl text-center">Sign Up</h1>

            <form onsubmit="return validate();" method="POST" novalidate class="form w-full"  autocomplete="off">
                {% csrf_token %}
                
                {{ form.non_field_errors }}

                {% if common_error %}
                    <div class="common-error">
                        {{ common_error }}
                    </div>
                {% endif %}

                <div class="row flex items-center gap-x-4">
                    <div class="form-group fname {% if form.first_name.errors %}error{% endif %}">
                        <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                        {{ form.first_name }}
                        
                        {{ form.first_name.errors }}
                    </div>
                    <div class="form-group lname {% if form.last_name.errors %}error{% endif %}">
                        <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                        {{ form.last_name }}
                        
                        {{ form.last_name.errors }}
                    </div>
                </div>

                <div class="form-group email {% if form.email.errors %}error{% endif %}">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                    {{ form.email }}
                    
                    {{ form.email.errors }}
                </div>

                <div class="form-group pwd1 {% if form.password1.errors %}error{% endif %}">
                    <label for="{{ form.password1.id_for_label }}">{{ form.password1.label }}</label>
                    {{ form.password1 }}
                    
                    {{ form.password1.errors }}
                </div>
                <div class="form-group pwd2 {% if form.password2.errors %}error{% endif %}">
                    <label for="{{ form.password2.id_for_label }}">{{ form.password2.label }}</label>
                    {{ form.password2 }}
                    
                    {{ form.password2.errors }}
                </div>

                <div class="form-group {% if form.role.errors %}error{% endif %}">
                    <label for="{{ form.role.id_for_label }}">I am a?</label>
                    {{ form.role }}
                    
                    {{ form.role.errors }}
                </div>

                <div id="common-error" class="text-sm mt-4 mb-2 text-red-500">
                </div>

                <button type="submit" class="btn btn-primary w-full font-bold mt-4 mb-4">Sign Up</button>
            </form>

            <p class="text-sm text-gray-500">Already have an account?
                <a href="{% url 'login' %}" class="font-bold">Login</a>
            </p>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        function validate() {
            // form element
            var form = document.querySelector('.form')

            // each input fields
            var fName = document.querySelector('#id_first_name').value
            var lName = document.querySelector('#id_last_name').value
            var email = document.querySelector('#id_email').value
            var pwd1 = document.querySelector('#id_password1').value
            var pwd2 = document.querySelector('#id_password2').value

            // <div> to render error
            let commonError = document.getElementById("common-error");

            function fNameValidation(name){
                var re =/^(?=.*[a-z])(?=.*[A-Z])/;
                return re.test(name);
            }

            function lNameValidation(name){
                var re = /^[a-zA-Z]+$/;
                return re.test(name);
            }

            function isEmailValid(email) {
                const re =/^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$/;
                return re.test(email);
            };

            function isPasswordSecure(password) {
                var re = /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})/;
                return re.test(password);
            };

            // first name validation
            if (fName == "") {
                commonError.innerHTML = 'First Name is required';

                return false
            } else if (!fNameValidation(fName)) {
                commonError.innerHTML = 'First Name include upper case and lower case';

                return false
            } else if (lName == "") {
                commonError.innerHTML = 'Last Name is required';

                return false
            } else if (!lNameValidation(lName)) {
                commonError.innerHTML = 'Invalid Last name';

                return false
            } else if (email == "") {
                commonError.innerHTML = 'Email is required';

                return false
            } else if (!isEmailValid(email)) {
                commonError.innerHTML = 'Invalid Email';

                return false
            } else if (pwd1 === "") {
                commonError.innerHTML = "Password cannot be empty";

                return false
            } else if (pwd2 === "") {
                commonError.innerHTML = "Confirm Password cannot be empty";

                return false
            } else if (pwd1 !== pwd2) {
                commonError.innerHTML = "Password's doesn't match";

                return false
            }  else if (!isPasswordSecure(pwd1)) {
                commonError.innerHTML = " password must atleast 8 character ,include atleast one number ,include both lower and upper case character";

                return false;
            } else {
                form.submit()
            }
        }
    </script>
{% endblock %}