findahome/findahome/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
#from properties import views

from django.conf.urls.static import static
from users.views import login_view,signup_view,logout_view,ChangePassword,forgetpswd
from properties import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('properties.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('login/',login_view,name='login'),
    path('signup/',signup_view,name='signup'),
    path("logout/", logout_view, name="logout"),
    path("change-password/<token>/",ChangePassword,name="change-password"),
    path("forgetpswd/",forgetpswd, name="forgetpswd"),   
    path("owner/",include('owner.urls')),   
    path('thanks/<int:reservation_id>/', views.thanks, name='thanks'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

findahome/owner/urls.py
from django.urls import path
from .views import properties_views,add_property, delete_property, update_property,request_views,accept_request,decline_request,other_request,view_maintenance_requests,price_prediction
#from .views import rental_map

app_name='owner'

urlpatterns = [
    path('',properties_views,name='properties'),
    path('add_property/',add_property,name='add_property'),
    path('delete_property/<int:property_id>/',delete_property,name='delete_property'),
    path('update_property/<int:property_id>/',update_property,name='update_property'),
    path('request/',request_views,name='request'),
    path('other-requests/',other_request, name='other_requests'),
    path('accept-request/<int:request_id>/',accept_request, name='accept_request'),
    path('decline-request/<int:request_id>/',decline_request, name='decline_request'),
    #path('map/', rental_map, name='rental_map'),
    path('view_maintenance_requests/',view_maintenance_requests,name='view_maintenance_requests'),
    path('price_prediction/',price_prediction,name='price_prediction'),
]

findahome/properties/urls.py
from django.urls import path
from .views import home
from .views import wishlist
from .views import search
from .views import reservation
from .views import property_details
from .views import add_comment
from .views import payment
from .views import thanks
from .views import terms
from .views import property_reserve,add_or_remove_wishlist
from .views import  create_maintenance_request,show_video
app_name='properties'

urlpatterns = [
    path('',home,name='home'),
    path('search/', search, name='search'),
    path('wishlist/',wishlist,name='wishlist'),
    path('reservation/',reservation,name='reservations'),
    path('property_details/<int:propertydetails_id>/',property_details,name='property_details'),
    path('property/reserve',property_reserve,name='property_reserve'),
    path('wishlists/property/<int:propertydetails_id>/',add_or_remove_wishlist, name='add_or_remove_wishlist'),
    path('property/<int:id>/add-comment', add_comment, name='add_comment'),
    path('payment/<int:property_id>/',payment,name='payment'),
    path('terms/<int:property_id>/',terms,name='terms'),
    path('maintenance_request/<int:property_id>/', create_maintenance_request,name='maintenancerequest'),
    #path('property/<int:property_id>/show_video/', show_video, name='show_video'),
    #path('show_video/<int:property_id>/', show_video, name='show_video'),
    path('show_video/<int:property_id>/', show_video, name='show_video'),
]

findahome/templates/base.html
{% load tailwind_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% tailwind_css %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

    <title>FindAHome -{%block title %} {%endblock%}</title>
    {%block tags %} {%endblock%}

</head>
<body class="relative">
  <div class="alerts-container fixed top-8 z-50 w-full flex justify-center">

  <div class="alerts" id="alerts">
    {% for message in messages %} 
      {% if message.tags %}
        <div role="alert" class="alert alert-{{ message.tags }}">
          {{ message }}

          <button class="close-btn" type="button">x</button>
        </div>
      {% else %}
        <div role="alert" class="alert alert-default">
          {{ message }}

          <button class="close-btn" type="button">x</button>
        </div>
      {% endif %} 
    {% endfor %}
  </div>
</div>

    <header class="header bg-white h-14 flex items-center justify-between container shadow fixed top-0 left-0 right-0 z-40 px-4">
    <a href="{% url 'properties:home' %}" class="logo font-sans text-primary font-bold text-2xl">
         findAhome<span class="text-rose-600">.com</span> </a>

      <div class="links flex items-center gap-x-4">
        {% if user.is_authenticated %}
       <!-- <a href="" class="text-primary">
            My Reservations
          </a>-->
          <div id="profile-container" class="profile-container relative text-gray-800">
            <button role="button" id="profile-btn" class="flex items-center gap-x-2">
              <img src="{{ user.profile_pic.url }}" alt="profile" class="profile w-7 h-7 rounded-full">
              <div class="info flex flex-col items-start">
                <span class="font-semibold text-sm">{{ user.first_name }} {{ user.last_name }}</span>
              </div>
              <div>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
              </div>
            </button>

            <ul style="display: none;" id="profile-dropdown" class="dropdown shadow rounded absolute top-12 right-0 bg-white w-44 z-40 flex-col">
             {% comment %} <li>
                <a class="text-gray-700 rounded-t px-4 py-2 border-b w-full hover:bg-gray-200 flex items-center gap-x-2" href="{% url 'properties:wishlist' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                  </svg>                  
                  Whishlist
                </a>
              </li> {% endcomment %}
              <li>
                <a class="text-gray-700 rounded-b px-4 py-2 w-full hover:bg-gray-200 flex items-center gap-x-2" href="">
                  <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>        
                  Profile
                </a>
              </li> 
              <li>
                <a class="text-gray-700 rounded-b px-4 py-2 w-full hover:bg-gray-200 flex items-center gap-x-2" href="{% url 'properties:reservations' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                  </svg>       
                  My Reservations
                </a>
              </li> 
              <li>
                <a class="text-gray-700 rounded-b px-4 py-2 w-full hover:bg-gray-200 flex items-center gap-x-2" href="{% url 'logout' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
                  </svg>           
                  Logout
                </a>
              </li> 
            </ul>
          </div>
        {% else %}
        <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
        <a href="{% url 'login' %}" class="btn text-primary">Login</a>
        {% endif %}
      </div>
    </header>
    <main class="content mt-14" style="min-height: 100vh;">
        {% block content %}{% endblock %}
    </main>
        
<footer class="footer mt-16 bg-black text-gray-200 w-full container py-4 text-sm px-4">
@ 2022 findAhome Inc.
</footer>
</body>

<script type="text/javascript">
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
    }
  var allCloseBtns = document.querySelectorAll(".close-btn");
  
  var profileBtn = document.getElementById('profile-btn')
  var profileDropdown = document.getElementById('profile-dropdown')

  if (profileBtn) {
    profileBtn.addEventListener('click', () => {
      if (profileDropdown.classList.contains('visible')) {
        profileDropdown.classList.remove('visible')
        profileDropdown.style.display = 'none';
      } else {
        profileDropdown.classList.add('visible')
        profileDropdown.style.display = 'flex';
      }
    })
  }
 
</script>
{% block script %}{% endblock %}
</body>
</html>

findahome/templates/base_auth.html
{% load static %} 
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    {% tailwind_css %}

    <title>FindAHome - {% block title %}{% endblock %}</title>
  </head>
  <body class="relative">
    {% if messages %}
      <div
        class="alerts-container absolute top-8 z-30 w-full flex justify-center"
      >
        <div class="alerts" id="alerts">
          {% for message in messages %} 
            {% if message.tags %}
              <div role="alert" class="alert alert-{{ message.tags }}">
                {{ message }}

                <button class="close-btn" type="button">x</button>
              </div>
            {% else %}
              <div role="alert" class="alert alert-default">
                {{ message }}

                <button class="close-btn" type="button">x</button>
              </div>
            {% endif %} 
          {% endfor %}
        </div>
      </div>
    {% endif %}

    <div class="auth-container w-screen h-screen flex overflow-x-hidden bg-blue-50"
  >
    <div class="image hidden md:block flex-1 w-full h-full">
      <img
        src="{% static 'img/house.jpeg' %}"
        alt="House"
        class="object-cover w-full h-full"
      />
    </div>
    <main class="form flex-1 flex items-center justify-center">
      {% block content %}{% endblock %}
    </main>
  </div>
  
  {% block script %}{% endblock %}
</body>
</html>

findahome/templates/base_owner.html
{% load tailwind_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    {% tailwind_css %}

    <title>FindAHome - {% block title %}{% endblock %}</title>

    
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}"> 
   
    {% block tags %}{% endblock %}
  </head>
  <body class="relative">
      <div class="alerts-container fixed top-8 z-50 w-full flex justify-center"
      >
        <div class="alerts" id="alerts">
          {% for message in messages %} 
            {% if message.tags %}
              <div role="alert" class="alert alert-{{ message.tags }}">
                {{ message }}

                <button class="close-btn" type="button">x</button>
              </div>
            {% else %}
              <div role="alert" class="alert alert-default">
                {{ message }}

                <button class="close-btn" type="button">x</button>
              </div>
            {% endif %} 
          {% endfor %}
        </div>
      </div>

    <header class="header bg-white h-14 flex items-center justify-between container shadow fixed top-0 left-0 right-0 z-40">
      <a href="{% url 'properties:home' %}" class="logo font-sans text-primary font-bold text-2xl flex items-center gap-x-1">
        
      </a>

      <div class="links flex items-center gap-x-4">
          <div id="profile-container" class="profile-container relative text-gray-800">
            <button role="button" id="profile-btn" class="flex items-center gap-x-2">
              <img src="{{ user.profile_pic.url }}" alt="profile" class="profile w-7 h-7 rounded-full">
              <div class="info flex flex-col items-start">
                <span class="font-semibold text-sm">{{ user.first_name }} {{ user.last_name }}</span>
              </div>
              <div>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
              </div>
            </button>

            <ul style="display: none;" id="profile-dropdown" class="dropdown shadow rounded absolute top-12 right-0 bg-white w-44 z-40 flex-col">
              <li>
                <a class="text-gray-700 rounded px-4 py-2 w-full hover:bg-gray-200 flex items-center gap-x-2" href="{% url 'logout' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
                  </svg>           
                  Logout
                </a>
              </li>
            </ul>
          </div>
      </div>
    </header>

    <div class="left flex">
        <aside class="owner-sidebar fixed top-14 left-0 bottom-0 bg-gray-900 w-56 pt-4 flex flex-col overflow-y-auto z-30">
            <nav class="h-full w-full">
                <ul class="invisible-scrollbar h-full w-full max-h-full overflow-y-auto flex flex-col">
                    {% url 'owner:properties' as owner_properties %}
                    <li>
                       <a href="{% url 'owner:properties' %}" class="owner-sidebar-item {% if request.path == owner_properties %}active{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M19.006 3.705a.75.75 0 00-.512-1.41L6 6.838V3a.75.75 0 00-.75-.75h-1.5A.75.75 0 003 3v4.93l-1.006.365a.75.75 0 00.512 1.41l16.5-6z" />
                            <path fill-rule="evenodd" d="M3.019 11.115L18 5.667V9.09l4.006 1.456a.75.75 0 11-.512 1.41l-.494-.18v8.475h.75a.75.75 0 010 1.5H2.25a.75.75 0 010-1.5H3v-9.129l.019-.006zM18 20.25v-9.565l1.5.545v9.02H18zm-9-6a.75.75 0 00-.75.75v4.5c0 .414.336.75.75.75h3a.75.75 0 00.75-.75V15a.75.75 0 00-.75-.75H9z" clip-rule="evenodd" />
                          </svg>
                          <span class="">Properties</span>
                       </a>
                    </li>

                    <li>
                      <a href="{% url 'owner:request' %}" class="owner-sidebar-item {% if request.path == owner_request %}active{% endif %}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 13.5h3.86a2.25 2.25 0 012.012 1.244l.256.512a2.25 2.25 0 002.013 1.244h3.218a2.25 2.25 0 002.013-1.244l.256-.512a2.25 2.25 0 012.013-1.244h3.859m-19.5.338V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18v-4.162c0-.224-.034-.447-.1-.661L19.24 5.338a2.25 2.25 0 00-2.15-1.588H6.911a2.25 2.25 0 00-2.15 1.588L2.35 13.177a2.25 2.25 0 00-.1.661z" />
                        </svg>
                        
                         <span class=""> Pending Request</span>
                      </a>
                   </li>
                    
                   <li>
                    <a href="{% url 'owner:other_requests' %}" class="owner-sidebar-item {% if request.path == owner_request_history %}active{% endif %}">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 13.5h3.86a2.25 2.25 0 012.012 1.244l.256.512a2.25 2.25 0 002.013 1.244h3.218a2.25 2.25 0 002.013-1.244l.256-.512a2.25 2.25 0 012.013-1.244h3.859m-19.5.338V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18v-4.162c0-.224-.034-.447-.1-.661L19.24 5.338a2.25 2.25 0 00-2.15-1.588H6.911a2.25 2.25 0 00-2.15 1.588L2.35 13.177a2.25 2.25 0 00-.1.661z" />
                      </svg>
                      
                       <span class="">Request History</span>
                    </a>
                 </li>
                 <li>
                  <a href="{% url 'owner:view_maintenance_requests' %}" class="owner-sidebar-item {% if request.path == owner_view_maintenance_requests %}active{% endif %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 13.5h3.86a2.25 2.25 0 012.012 1.244l.256.512a2.25 2.25 0 002.013 1.244h3.218a2.25 2.25 0 002.013-1.244l.256-.512a2.25 2.25 0 012.013-1.244h3.859m-19.5.338V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18v-4.162c0-.224-.034-.447-.1-.661L19.24 5.338a2.25 2.25 0 00-2.15-1.588H6.911a2.25 2.25 0 00-2.15 1.588L2.35 13.177a2.25 2.25 0 00-.1.661z" />
                    </svg>
                    
                     <span class="">Maintenance Request</span>
                  </a>
               </li>
               <li>
                <a href="{% url 'owner:price_prediction' %}" class="owner-sidebar-item {% if request.path == owner_price_prediction %}active{% endif %}">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 8.25H9m6 3H9m3 6l-3-3h1.5a3 3 0 100-6M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  
                  
                   <span class="">House price Prediction</span>
                </a>
             </li>
                 </ul>
            </nav>
        </aside>
        <main class="content mt-14 flex-1 ml-56 px-8 pt-10" style="min-height: 100vh;">
            {% block content %}{% endblock %}
        </main>
    </div>

    <footer class="footer mt-16 bg-black text-gray-200 ml-56 w-full container py-4 text-sm">
      &copy; 2022 findAhome Inc.
    </footer>
    <script type="text/javascript">
      var allCloseBtns = document.querySelectorAll(".close-btn");
    
     
      var profileBtn = document.getElementById('profile-btn')
      var profileDropdown = document.getElementById('profile-dropdown')
    
      if (profileBtn) {
        profileBtn.addEventListener('click', () => {
          if (profileDropdown.classList.contains('visible')) {
            profileDropdown.classList.remove('visible')
            profileDropdown.style.display = 'none';
          } else {
            profileDropdown.classList.add('visible')
            profileDropdown.style.display = 'flex';
          }
        })
      }
    </script>
    {% block script %}{% endblock %}
  </body>
</html>